name: quiz_app
description: A server app using the shelf package and Docker.
version: 1.0.0

publish_to: none

environment:
  sdk: '^3.5.0'

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  json_annotation: ^4.9.0
  path: ^1.9.1

  yaroorm: 
    git:
      url: https://github.com/codekeyz/yaroorm.git
  ez_validator_dart:
    git:
      url: https://github.com/codekeyz/ez-validator-yaroo.git
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.14.0
  dotenv: ^4.2.0

dev_dependencies:
  json_serializable: ^6.8.0
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.13
